"""add source status

Revision ID: e8c980531c4f
Revises: 
Create Date: 2026-05-18 16:37:50.137691

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e8c980531c4f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('voltage_readings', sa.Column('source_s1_ok', sa.Boolean(), nullable=True))
    op.add_column('voltage_readings', sa.Column('source_s2_ok', sa.Boolean(), nullable=True))
    op.add_column('voltage_readings', sa.Column('source_s3_ok', sa.Boolean(), nullable=True))
    op.add_column('voltage_readings', sa.Column('priority_s1', sa.Integer(), nullable=True))
    op.add_column('voltage_readings', sa.Column('priority_s2', sa.Integer(), nullable=True))
    op.add_column('voltage_readings', sa.Column('priority_s3', sa.Integer(), nullable=True))
    op.add_column('voltage_readings', sa.Column('delay_ta', sa.BigInteger(), nullable=True))
    op.add_column('voltage_readings', sa.Column('delay_tb', sa.BigInteger(), nullable=True))
    op.add_column('voltage_readings', sa.Column('uptime', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('voltage_readings', 'uptime')
    op.drop_column('voltage_readings', 'delay_tb')
    op.drop_column('voltage_readings', 'delay_ta')
    op.drop_column('voltage_readings', 'priority_s3')
    op.drop_column('voltage_readings', 'priority_s2')
    op.drop_column('voltage_readings', 'priority_s1')
    op.drop_column('voltage_readings', 'source_s3_ok')
    op.drop_column('voltage_readings', 'source_s2_ok')
    op.drop_column('voltage_readings', 'source_s1_ok')
    # ### end Alembic commands ###
